name: Rust Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install libusb
      run: sudo apt install -y libusb-dev libusb-1.0
      if: matrix.os == 'ubuntu-latest'
    - uses: actions/checkout@v2.3.1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
