name: Rust Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install libusb and libftdi
        run: |
          sudo apt update
          sudo apt install -y libusb-1.0-0-dev libftdi1-dev
        if: matrix.os == 'ubuntu-latest'

      - name: Install libftdi (windows)
        uses: lukka/run-vcpkg@v5
        with:
          vcpkgArguments: "libftdi1:x64-windows"
          # Version including bugfix for libusb (see https://github.com/microsoft/vcpkg/issues/12642)
          vcpkgGitCommitId: "6ed0bc982bf9bdca25439d538f7f272786a7af4d"
          vcpkgTriplet: x64-windows
        if: matrix.os == 'windows-latest'

      - uses: actions/checkout@v2.3.4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
